services:
  order-service-mysql:
    image: mysql:8.4
    container_name: order-service-mysql
    profiles: ["order"]
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3306:3306"
    volumes:
      - order_service_mysql_data:/var/lib/mysql

  debugger-service-mysql:
    image: mysql:8.4
    container_name: debugger-service-mysql
    profiles: ["debugger"]
    environment:
      MYSQL_DATABASE: debuggerdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3307:3306"
    volumes:
      - debugger_service_mysql_data:/var/lib/mysql

  kafka:
    image: apache/kafka:4.1.2
    container_name: local-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@local-kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

volumes:
  order_service_mysql_data:
  debugger_service_mysql_data:
